DATABASE_URL = "postgresql://postgres.ldunpssoxvifemoyeuac:SIHCLI-POTER123*@aws-1-us-east-2.pooler.supabase.com:6543/postgres"
# --------------------------------------------------------
# DEJA AL MENOS 2 LÍNEAS EN BLANCO AQUÍ
# --------------------------------------------------------


# --- SECCIÓN IRI (NUEVA) ---
# ¡IMPORTANTE! El corchete [ debe estar pegado a la izquierda.
[iri]
username = "omejiariv"
password = "k2xpfeNLBW"


# --------------------------------------------------------


SUPABASE_URL = "https://ldunpssoxvifemoyeuac.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkdW5wc3NveHZpZmVtb3lldWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNDk1NzQsImV4cCI6MjA3ODkyNTU3NH0.UDlf1aFBDCR8WS87ldS_D3cUl3g0HVfIVoekn1ZBAkI"